# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 519d6926b4ff8a12797ac676a221c12a7d07e8efacfb94bbec0060784292f989519746d8b883757826d7c6957d6512f9c49f99e9e748e1cc80f18cb5e1b05b55

test:
  secret_key_base: 8e364346650616b7a667e282b909f58dac7bff2a4d747750b5d8cb9023d06b267a1c43864701a92b1b043d60dc49e6844ac364d7b048d41e07d8be1fc140798f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
